spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  profiles:
    include: key
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  resources:
    static-locations: -classpath:/static/**
  mvc:
    static-path-pattern: /static/**

server:
  port: 753

mybatis:
  mapper-locations: /mapper/**/*.xml
  type-aliases-package: com.ssh.sustain.model

logging:
  level:
    jdbc:
      connection: off
      sqlonly: off
      sqltimeing: info
      resultset: off
      resultsettable: info
      audit: off
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace