#hibernate
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    include: key
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

#logging
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

server:
  port: 753

mybatis:
  mapper-locations: /mapper/**/*.xml
  type-aliases-package: com.ssh.sustain.model